"""Verbatim-shaped PR bodies from the 2026-09-21 verification run (trimmed)."""

SECURE_REPO_BODY = """## Summary

This pull request is created by [StepSecurity](https://app.stepsecurity.io/securerepo) at the request of @pniedzielski. Please merge the Pull Request to incorporate the requested changes. Please tag @pniedzielski on your message if you have any questions related to the PR.
## Security Fixes

### Least Privileged GitHub Actions Token Permissions

## Feedback
For bug reports, feature requests, and general feedback; please email support@stepsecurity.io.

Signed-off-by: StepSecurity Bot <bot@stepsecurity.io>
"""

SECURE_REPO_BODY_2022 = "Please look at the file changes for more details"

APP_BODY = """## Summary

This pull request has been generated by [StepSecurity](https://app.stepsecurity.io/github/codota/actions/dashboard) as part of your enterprise subscription to ensure compliance with recommended security best practices. Please review and merge the pull request to apply these security enhancements.

## Security Fixes

### Pinned Dependencies
"""

INT_BODY = """## Summary

This pull request has been generated by [StepSecurity](https://int1.stepsecurity.io/github/vamshi-stepsecurity/actions/dashboard) as part of your enterprise subscription to ensure compliance with recommended security best practices.
"""

REVERT_BODY = """Reverts chainguard-dev/actions#689


@eslerm @jml @jmeridth we need to revert this change because if some consumer outside of Chainguard is using it will fail because this needs a valid license
"""
